version: "3"
services:
  app:
    build: .
    volumes:
      - ./downloads:/usr/src/app/downloads
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  webnet:
